name: remove_unused_resources
on:
  schedule:
    - cron: "30 9 1 * *"

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Copy CI gradle.properties
      run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

    - name: Add GitHub Packages auth
      run: ./scripts/ci-github-packages-properties.sh

    - name: Setup JDK 17
      uses: actions/setup-java@v3.12.0
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        # Only write to the cache for builds on the 'develop' branch
        cache-read-only: ${{ github.ref != 'refs/heads/develop' }}
        gradle-home-cache-cleanup: true

    - name: Prebuild
      run: ./scripts/ci-prebuild.sh
      env:
        LOKALISE_ID: ${{ secrets.LOKALISE_ID }}
        LOKALISE_TOKEN: ${{ secrets.LOKALISE_TOKEN }}
        ADYEN_CLIENT_KEY: ${{ secrets.ADYEN_CLIENT_KEY_TEST }}

    - name: Run android lint
      run: ./gradlew :app:app:lintDebug -Prur.lint.onlyUnusedResources

    - name: Remove unused resources
      run: ./gradlew :app:app:removeUnusedResources -Prur.lintVariant="debug"

    - name: Generate Token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.CI_APP_ID }}
        private_key: ${{ secrets.CI_APP_PRIVATE_KEY }}

    - name: Create PR
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ steps.generate_token.outputs.token }}
        branch: "maintenance/remove-unused-resources"
        title: "Maintenance: Remove unused resources"
        body: ""
